# Generated by Django 5.0.7 on 2026-07-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(help_text='Enter 10 digits phone number', max_length=10, unique=True, verbose_name='Phone Number'),
        ),
    ]
